### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by guomouren** [victordrumond/react-movie-app#1]
Hello, sir
    I tried to start the app according to the prompt steps of readme, but it reported an error, as follows:
`bash: npm start

> react-movie-app@1.0.0 start /Users/xxx/web/react-movie-app
> node server/index.js

/Users/xxx/web/react-movie-app/node_modules/mongoose/node_modules/mongodb/lib/bson.js:10
catch { } // eslint-disable-line
      ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xxx/web/react-movie-app/node_modules/mongoose/node_modules/mongodb/lib/utils.js:8:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-movie-app@1.0.0 start: `node server/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-movie-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2022-05-26T05_02_38_252Z-debug.log`

The running environment is ready. Please help me solve it

**Comment by guomouren** [comment]
The problem has been solved and needs to be solved according to package.json update node version, thank you
